name: Security Scan

on:
  workflow_dispatch:

jobs:
  scan-docker-images:
    name: Scan Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build frontend image
        run: |
          cd frontend
          docker build -t frontend:${{ github.sha }} .

      - name: Build backend image
        run: |
          cd backend
          docker build -t backend:${{ github.sha }} .

      - name: Scan frontend image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'frontend:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-frontend-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Scan backend image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'backend:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-backend-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload frontend scan results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-frontend-results.sarif'
          category: 'frontend-container'

      - name: Upload backend scan results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-backend-results.sarif'
          category: 'backend-container'

  scan-infrastructure:
    name: Scan Infrastructure Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup TFSec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: infra
          format: sarif
          out: tfsec-results.sarif

      - name: Upload infrastructure scan results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'tfsec-results.sarif'
          category: 'terraform'